debug: true
web:
  host: 127.0.0.1
  port: 8000

sentry:
  dsn:
  env: dev

session:
  key: CaY5iCkYtN7DqXdiYK1BvmGrQuaSA4Tl4bEk9my0jc0=

admin:
  email: admin@admin.com
  password: admin

database:
  host: 127.0.0.1
  port: 5432
  user: postgres
  password: HunteR321
  database: pr

bot:
  token: vk1.a.8VXIelgt4ECXO1mpuUEdSS2TOeEw4vfdTzPI761pMW46psK5hmm6ySadU-88gCQj19A9PzVaGnA-sKgbhIEnSMrwlInW243s76EKqCCHFYQPp-b2FbtJ5zvV1aCyMthnfaUy6iMQ-bAWztR7JCZKIHKiEQpPLL35qbh50tXwQ-jgCyYvI-fpZiiYLU36_eAIeWiwKECA1xHoKfsdykgqkA
  group_id: 158327634

store: {}
